services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    restart: unless-stopped
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/lib/tempo
    environment:
      - TEMPO_STORAGE_BACKEND=local
      - TEMPO_LOCAL_STORAGE_PATH=/var/lib/tempo
    ports:
      - "3200:3200"   # tempo
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: [ "-config.file=/etc/loki/config.yaml" ]
    restart: unless-stopped
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    depends_on:
      - loki
      - tempo
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
volumes:
  grafana-storage: {}
  tempo-storage: {}
  tempo-data: {}
  loki-data: {}